docker-compose-yaml: docker-compose.yml

endpoint: ssh.develop.amazeeio.review:32222
ssh: ssh.develop.amazeeio.review:32222
api: https://api-lagoon-dev-develop.us.amazee.io

project: ben-test

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    - run:
        name: IF no Drupal installed and we are not master branch, sync from master brancy
        command: |
            if tables=$(drush sqlq "show tables like 'node';") && [ -z "$tables" ]; then
                # no drupal installed, we install drupal from scratch
                drush -y site-install config_installer
            fi
        service: cli
        shell: bash
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

production_routes:
  active:
    routes:
      - nginx:
         - ben-test-active.au.amazee.io
         - ben-test-production.au.amazee.io
  standby:
    routes:
      - nginx:
         - ben-test-standby.au.amazee.io
